name: tanari_app
description: "Una aplicacion desarrollada para el Trabajo de Fin de Grado de la UNEXPO, donde la tematica es un Dispositivo portatil para monitoreo de gases de efecto invernadero con acople a un vehiculo terrestre no tripulado (UGV). Esta aplicacion es una de las 3 partes del proyecto llamado TANARi. Esta nos permitira visualizar, controlar, almacenar y gestionar por usuario la data en el monitoreo GEI..."
publish_to: 'none'
version: 1.6.2

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3 # Almacenamiento local de preferencias del usuario
  http: ^1.4.0 # Para realizar peticiones HTTP
  flutter_blue_plus: ^1.35.5 # Plugin para conectividad Bluetooth
  permission_handler: ^12.0.0+1 # Permisos para acceder a funcionalidades del dispositivo
  get: ^4.7.2 # Manejo de estado y dependencias
  device_info_plus: ^11.4.0 # Informacion del dispositivo
  logger: ^2.5.0 # Para registro de logs
  icons_plus: ^5.0.0 # Iconos adicionales
  sqflite: ^2.4.2 # Base de datos local para almacenamiento de datos
  path: ^1.8.3 # Manejo de rutas de archivos
  logging: ^1.3.0 # Registro de eventos y errores
  collection: ^1.19.1 # Utilidades de colecciones
  supabase_flutter: ^2.9.1  # Supabase para autenticacion y almacenamiento de datos
  image_picker: ^1.1.2 # Seleccion de imagenes desde la galeria o camara
  image_cropper: ^9.1.0 # Recorte de imagenes
  intl: ^0.20.2 # Internacionalizacion y formateo de fechas
  fl_chart: ^0.65.0  # Gráficos y visualización de datos
  app_links: ^6.4.0 # Manejo de enlaces universales
  url_launcher: ^6.3.2 # Abrir enlaces en el navegador o aplicaciones externas
  flutter_map: ^8.2.1 # Mapas interactivos
  latlong2: ^0.9.1 # Manejo de coordenadas geograficas 
  mapbox_maps_flutter: ^2.10.0 # Mapas de Mapbox con funcionalidades avanzadas y personalizacion 
  geolocator: ^14.0.2 # Geolocalizacion y servicios de ubicacion
  map_launcher: ^4.4.2 # Navegacion entre aplicaciones de mapas
  flutter_svg: ^2.0.7 # Soporte para imagenes SVG
  clipboard: ^0.1.3 # Manejo del portapapeles del dispositivo \
  pdf: ^3.10.8 # Generacion de documentos PDF
  printing: ^5.12.0 # Impresion de documentos
  path_provider: ^2.1.3 # Acceso a rutas del sistema de archivos
  open_file: ^3.2.1 # Abrir archivos con aplicaciones externas


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    #Imagenes para el login e inicio de sesion
    - assets/images/login_1.png
    - assets/images/login_bg.png